version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '1234567'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: '1234567'
    ports:
      - '3306:3306'
